---
author: Chris Alef
baseurl: "" # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
  Navigating King County’s social-services landscape can be complex—even for experienced professionals. King County Solutions streamlines the process by bringing publicly available regional resources together in one searchable, easy-to-use platform.
collections:
  organizations:
    output: true
    permalink: /organizations/:name/
  places:
    output: true
    permalink: /places/:name/
  topics:
    output: true
    permalink: /topics/:name/
defaults:
    - scope:
        path: "_topics"
        type: "topics"
      values:
        layout: "topic"
    - scope:
          path: "_posts"
          type: "posts"
      values:
        layout: "post"
    - scope:
        path: "_organizations"
        type: "organizations"
      values:
        layout: "organization"
    - scope:
        path: "_places"
        type: "places"
      values:
        layout: "place"
email: chris@crickertech.com
exclude:
  - .jekyll-cache/
  - .sass-cache/
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bin/
  - gemfiles/
  - lib/
  - script/
  - vendor/
github_username: calef
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
theme: minima
future: true
pagination:
  enabled: true
  collection: 'posts'
  per_page: 20
  permalink: '/page:num/'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
title: King County Solutions
url: "https://kingcountysolutions.netlify.app"
