---
baseurl: "" # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
  Navigating social services can be confusing. This project makes it simple by bringing publicly available resources together in one searchable, easy-to-use platform. Whether youâ€™re an individual looking for help or a nonprofit guiding clients, you can quickly find the support you need.
collections:
  organizations:
    output: true
    permalink: /organizations/:name/
  places:
    output: true
    permalink: /places/:name/
  topics:
    output: true
    permalink: /topics/:name/
defaults:
    - scope:
        path: "_topics"
        type: "topics"
      values:
        layout: "topic"
    - scope:
          path: "_posts"
          type: "posts"
      values:
        layout: "post"
    - scope:
        path: "_organizations"
        type: "organizations"
      values:
        layout: "organization"
    - scope:
        path: "_places"
        type: "places"
      values:
        layout: "place"
email: chris@crickertech.com
exclude:
  - .jekyll-cache/
  - .sass-cache/
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bin/
  - gemfiles/
  - lib/
  - script/
  - vendor/
github_username: calef
organizations_schema:
  title:
    description: 'The name of the organization.'
    type: string
    rules:
    - The field is required.
    - The field value is unique across all organizations.
    examples:
    - Administration for Community Living
    - Aging and Long-Term Support Administration
    - Auburn School District
    - Beehave Academy
    - Behavioral Health Administration
  acronym:
    description: 'The acronym that the organization calls itself by.'
    type: string | nilclass
    rules:
    - The field is optional.
    - The field value is unique across all organizations.
    examples:
    - ACL
    - ALTSA
    - ASD
    - BHA
    - BSD
  website:
    description: "The URL for the organization's website."
    type: string
    rules:
    - The field is required.
    - The string is a valid URL.
    - The field value is unique across all organizations.
    examples:
    - https://acl.gov/
    - https://www.auburn.wednet.edu
    - https://www.beehaveacademy.com/
    - https://www.dshs.wa.gov/altsa
    - https://www.dshs.wa.gov/bha
  parent_organization:
    description: 'The name of the parent organization, if such a parent exists.'
    type: string
    rules:
    - The field does not exist or it is the title of another organization.
    - The field value cannot be equal to the title.
    examples:
    - City of Bellevue
    - Department of Community and Human Services
    - Department of Health and Human Services
    - Department of Social and Health Services
    - Puget Sound Educational Service District 121
  type:
    description: 'The type of the organization.'
    type: string
    rules:
    - The field is required.
    examples:
    - Agency
    - Community-Based Organization
    - Division
    - Program
    - School District
  email:
    description: 'The contact email address of the organization.'
    type: string
    rules:
    - The field is optional.
    - The field value is an email address.
    - The value is unique across all organizations.
    examples:
    - amberrae@beehaveacademy.com
    - info@cisc-seattle.org
  address:
    description: 'The contact address of the organization.'
    type: string
    rules:
    - The field is optional.
    - The value is a valid mailing address.
    examples:
    - 10885 NE 4th St., Ste 710 (7th Floor), Bellevue, WA 98004
    - 179 1st Ave SE, Issaquah, WA 98027
    - 611 S Lane St., Seattle, WA 98104
    - 7722 Center Blvd SE, Snoqualmie, WA 98065
    - 9050 384th Ave. SE, Snoqualmie, WA 98065
  phone:
    description: 'The contact North American 10 digit phone number of the organization.'
    rules:
    - The field is optional.
    - The value is a ten digit phone number in the form 999-999-9999.
    type: string
    examples:
    - 206-624-5633
    - 425-392-4123
    - 425-754-6276
    - 425-888-3347
  events_ical_url:
    description: 'The URL for the ical events calendar of the organization.'
    type: string
    rules:
    - The field is optional.
    - The field value is a valid URL.
    - The contents of the URL is a valid ical file.
    examples:
    - https://cisc-seattle.org/events/?ical=1
    - https://empoweryouthnetwork.org/events/?ical=1
    - https://iacswa.org/events/?ical=1
    - https://kidvantagenw.org/events/?ical=1
    - https://togethercenter.org/events/?ical=1
  news_rss_url:
    description: "The URL of the RSS feed for the organization's news."
    type: string
    rules:
    - The field is optional.
    - The field value is a valid URL.
    - The contents of the URL is an RSS feed.
    examples:
    - https://cisc-seattle.org/feed
  topics:
    description: 'The topics that the organization relates to.'
    type: array
    rules:
    - The field is required.
    possible_values:
    - Adult Education
    - Advocacy
    - Assistive Technology
    - Bus Fare
    - Childcare
    - Clothing
    - Community & Social Services
    - Crisis Hotlines
    - Dental Care
    - Diagnostic Testing
    - Diapers
    - Disabilities
    - Domestic Violence
    - Early Intervention
    - Education & Learning
    - Employment
    - Employment & Job Support
    - ESL Classes
    - Financial Assistance
    - Financial Counseling
    - Financial Support
    - Food & Nutrition
    - Food Pantries/Banks
    - Free Meals
    - Gas Money
    - GED Classes
    - General Counseling Services
    - Grocery Delivery
    - Health Care
    - Home Delivered Meals
    - Homeless Day Centers
    - Homeless Student Liaison
    - Hotline
    - Household Goods
    - Hygiene Items
    - Job Search
    - Job Seeking Skills
    - Legal Aid
    - Local Transportation
    - Mental Health & Counseling
    - Mental Health Evaluation
    - Move-in Assistance
    - Overnight Shelters
    - Paratransit Services
    - Permanent Housing
    - Personal & Household Needs
    - Primary Care
    - Recreation/Community Programs
    - Rent Assistance
    - Senior Meals
    - Senior Services
    - Shelter
    - Shelter & Housing
    - Specialized Clinics
    - Support Groups
    - Teen Clinics
    - Teen Counseling
    - Transitional Housing
    - Transportation & Mobility
    - Traumatic Brain Injury Services
    - Tutoring/Homework Help
    - Utility Assistance
    - Utility Discounts
    - Vocational Training
    - Volunteer Opportunities
    - Youth Employment Programs
    - Youth Shelter
  jurisdictions:
    description: 'The list of jurisdictions that the organizations operates within or supports.'
    type: array
    rules:
    - The field is required.
    - Each jurisdiction value in the array is the title of a place in the places collection.
    examples:
    - Snoqualmie, North Bend, Fall City
    - Seattle
    - King County
places_schema:
  parent_place:
    description: 'The name of the next larger place that this place is fully incorporated within.'
    type: string
    rules:
    - The field does not exist if it does not have a parent place.
    - The value is a title of another place.
    examples:
    - King County
    - United States
    - Washington State
  title:
    description: 'The name of the place.'
    type: string
    rules:
    - The field is required.
    - The title is unique across all other places.
    examples:
    - Algona
    - Ames Lake
    - Auburn
    - Baring
    - Beaux Arts Village
  type:
    description: 'The type of place.'
    type: string
    rules:
    - The field is required.
    - The field value is one of the possible_values.
    possible_values:
    - Census-Designated Place
    - City
    - Country
    - County
    - Town
  zip_codes:
    description: 'The US postal service zip codes that correspond with the place.'
    type: array
    rules:
    - Each item in the array is composed of five digits.
    examples:
    - '98001'
    - '98004'
    - '98053'
    - '98224'
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
theme: minima
pagination:
  enabled: true
  collection: 'posts'
  per_page: 20
  permalink: '/page:num/'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
topics:
  Community & Social Services:
    - Childcare
    - Legal Aid
    - Recreation/Community Programs
    - Senior Services
    - Volunteer Opportunities
  Disabilities:
    - Assistive Technology
    - Early Intervention
    - Employment
    - Financial Support
    - Traumatic Brain Injury Services
  Domestic Violence:
    - Advocacy
    - Hotline
    - Shelter
  Education & Learning:
    - Adult Education
    - ESL Classes
    - GED Classes
    - Homeless Student Liaison
    - Tutoring/Homework Help
  Employment & Job Support:
    - Job Search
    - Job Seeking Skills
    - Vocational Training
    - Youth Employment Programs
  Financial Assistance:
    - Financial Counseling
    - Move-in Assistance
    - Rent Assistance
    - Utility Assistance
    - Utility Discounts
  Food & Nutrition:
    - Food Pantries/Banks
    - Free Meals
    - Grocery Delivery
    - Home Delivered Meals
    - Senior Meals
  Health Care:
    - Dental Care
    - Diagnostic Testing
    - Primary Care
    - Specialized Clinics
    - Teen Clinics
  Mental Health & Counseling:
    - Crisis Hotlines
    - General Counseling Services
    - Mental Health Evaluation
    - Support Groups
    - Teen Counseling
  Personal & Household Needs:
    - Clothing
    - Diapers
    - Household Goods
    - Hygiene Items
  Shelter & Housing:
    - Homeless Day Centers
    - Overnight Shelters
    - Permanent Housing
    - Transitional Housing
    - Youth Shelter
  Transportation & Mobility:
    - Bus Fare
    - Gas Money
    - Local Transportation
    - Paratransit Services
topics_schema:
  title:
    description: 'the name of the topic'
    type: string
    examples:
    - Adult Education
    - Advocacy
    - Assistive Technology
    - Bus Fare
    - Childcare
  parent_topic:
    description: 'The name of the parent topic that this topic a subtopic of. If there is no parent_topic, then this topic is a top-level topic.'
    type: string
    examples:
    - Community & Social Services
    - Disabilities
    - Domestic Violence
    - Education & Learning
    - Transportation & Mobility
title: King County Solutions
url: "https://kingcounty.solutions"
